import { SkinProject } from './schema';
import { PLATFORM_ASSETS } from './platformAssets';
import { CHARACTER_BANK } from './characterBank';
import { migrateProjectIdentities } from './identity';

// Pre-defined example conversations matching the Examples Gallery
// Writers can load these as starting points for quick wins

// CDN base for character avatars (CHARACTER_BANK in characterBank.ts provides 30 pre-loaded options)
const AVATAR_CDN = '/assets';

export const TEMPLATE_EXAMPLES: Record<string, SkinProject[]> = {
  // ========== TWITTER/X EXAMPLES (3) ==========
  twitter: [
    {
      id: 'twitter-character-thread',
      template: 'twitter',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#1DA1F2',
        receiverColor: '#f5f8fa',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 600,
        useDarkNeutral: true,
        watermark: true,
        twitterDisplayName: 'Alex Rivers',
        twitterHandle: 'alexrivers',
        twitterVerified: true,
        twitterAvatarUrl: `${AVATAR_CDN}/alex-avatar.png`,
        twitterShowMetrics: true,
        twitterThreadMode: true,
        twitterTimestamp: '2:15 PM · Nov 26, 2025',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
        twitterCharacterPresets: [
          { id: 'char1', name: 'Alex Rivers', handle: 'alexrivers', verified: true, avatarUrl: `${AVATAR_CDN}/alex-avatar.png` }
        ]
      },
      messages: [
        { id: '1', sender: 'Alex Rivers', content: "okay so I need to tell you all something\n\nthis is going to be a thread 🧵", outgoing: true, timestamp: '2:15 PM', twitterLikes: 847, twitterRetweets: 89, twitterReplies: 156, useCustomIdentity: true, twitterHandle: 'alexrivers', avatarUrl: `${AVATAR_CDN}/alex-avatar.png`, verified: true },
        { id: '2', sender: 'Alex Rivers', content: "first of all, I never expected this to happen\n\nbut here we are", outgoing: true, timestamp: '2:16 PM', twitterLikes: 623, twitterRetweets: 34, twitterReplies: 67, parentId: '1', useCustomIdentity: true, twitterHandle: 'alexrivers', avatarUrl: `${AVATAR_CDN}/alex-avatar.png`, verified: true },
        { id: '3', sender: 'Alex Rivers', content: "and I know you're all going to have opinions about this\n\nbut honestly? I don't care anymore", outgoing: true, timestamp: '2:18 PM', twitterLikes: 1103, twitterRetweets: 198, twitterReplies: 289, parentId: '2', useCustomIdentity: true, twitterHandle: 'alexrivers', avatarUrl: `${AVATAR_CDN}/alex-avatar.png`, verified: true },
      ]
    },
    {
      id: 'twitter-verified-account',
      template: 'twitter',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#1DA1F2',
        receiverColor: '#f5f8fa',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 600,
        useDarkNeutral: true,
        watermark: true,
        twitterDisplayName: 'Taylor Swift',
        twitterHandle: 'taylorswift13',
        twitterVerified: true,
        twitterAvatarUrl: `${AVATAR_CDN}/Taylor-Swift-avatar.png`,
        twitterShowMetrics: true,
        twitterThreadMode: false,
        twitterTimestamp: '12:00 PM · Nov 26, 2025',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
        twitterCharacterPresets: [
          { id: 'char1', name: 'Taylor Swift', handle: 'taylorswift13', verified: true, avatarUrl: `${AVATAR_CDN}/Taylor-Swift-avatar.png` }
        ]
      },
      messages: [
        { id: '1', sender: 'Taylor Swift', content: "Big news coming tonight at midnight 🌙✨\n\nI can't wait to share this with you all", outgoing: true, timestamp: '12:00 PM', twitterLikes: 2847293, twitterRetweets: 189473, twitterReplies: 45821, twitterViews: 15200000, useCustomIdentity: true, twitterHandle: 'taylorswift13', avatarUrl: `${AVATAR_CDN}/Taylor-Swift-avatar.png`, verified: true },
      ]
    },
    {
      id: 'twitter-media-image',
      template: 'twitter',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#1DA1F2',
        receiverColor: '#f5f8fa',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 600,
        useDarkNeutral: true,
        watermark: true,
        twitterDisplayName: 'Jamie Chen',
        twitterHandle: 'jamiechen',
        twitterVerified: false,
        twitterAvatarUrl: `${AVATAR_CDN}/Jamie-Chen-avatar.png`,
        twitterShowMetrics: true,
        twitterThreadMode: false,
        twitterTimestamp: '5:42 PM · Nov 26, 2025',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
        twitterCharacterPresets: [
          { id: 'char1', name: 'Jamie Chen', handle: 'jamiechen', verified: false, avatarUrl: `${AVATAR_CDN}/Jamie-Chen-avatar.png` }
        ]
      },
      messages: [
        { 
          id: '1', 
          sender: 'Jamie Chen', 
          content: "caught the most incredible sunset today 🌅\n\nsometimes you just have to stop and appreciate the moment", 
          outgoing: true, 
          timestamp: '5:42 PM', 
          twitterLikes: 2431, 
          twitterRetweets: 128, 
          twitterReplies: 89, 
          attachments: [{ type: 'image', url: 'https://placehold.co/600x338/dde8f0/778899?text=📷+Add+your+image' }],
          useCustomIdentity: true, 
          twitterHandle: 'jamiechen', 
          avatarUrl: `${AVATAR_CDN}/Jamie-Chen-avatar.png`, 
          verified: false 
        },
      ]
    },
  ],

  // ========== iOS iMESSAGE EXAMPLES (3) ==========
  ios: [
    {
      id: 'ios-two-person-chat',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: 'Sam',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'Sam', content: 'hey', outgoing: false, timestamp: '10:23' },
        { id: '2', sender: 'You', content: 'hi!', outgoing: true, timestamp: '10:24' },
        { id: '3', sender: 'Sam', content: 'you free tonight?', outgoing: false, timestamp: '10:24' },
        { id: '4', sender: 'You', content: 'yeah why', outgoing: true, timestamp: '10:25' },
        { id: '5', sender: 'Sam', content: 'want to grab dinner?', outgoing: false, timestamp: '10:25' },
        { id: '6', sender: 'You', content: "I'd love to", outgoing: true, timestamp: '10:26', status: 'read' },
      ]
    },
    {
      id: 'ios-contact-avatar',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: 'Jordan',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: `${AVATAR_CDN}/jordan-avatar.png`,
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'Jordan', content: "did you see what they posted?!", outgoing: false, timestamp: '3:15' },
        { id: '2', sender: 'You', content: 'NO what happened', outgoing: true, timestamp: '3:16' },
        { id: '3', sender: 'Jordan', content: "I'm sending you the screenshot", outgoing: false, timestamp: '3:16' },
        { id: '4', sender: 'Jordan', content: "you're not going to believe this", outgoing: false, timestamp: '3:16' },
        { id: '5', sender: 'You', content: 'JORDAN', outgoing: true, timestamp: '3:17' },
        { id: '6', sender: 'You', content: 'TELL ME', outgoing: true, timestamp: '3:17', status: 'read' },
      ]
    },
    {
      id: 'ios-typing-indicators',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: 'Riley',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: `${AVATAR_CDN}/Riley-avatar.png`,
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'You', content: 'I have something to tell you', outgoing: true, timestamp: '11:47 PM' },
        { id: '2', sender: 'Riley', content: 'okay?', outgoing: false, timestamp: '11:48 PM' },
        { id: '3', sender: 'You', content: "it's about what happened last week", outgoing: true, timestamp: '11:49 PM', status: 'read' },
        { id: '4', sender: 'Riley', content: '...', outgoing: false, timestamp: '', isTyping: true },
      ]
    },
    {
      /**
       * Every structured iOS block in one scene, so the feature can be looked
       * at rather than read about. A feature that is only representable in JSON
       * is not implemented (§0.2).
       *
       * The audio is a known CORS-enabled MP3 rather than the W3 `.oga` sample
       * that stalls under AO3's anonymous-CORS playback — the one detail of
       * this example that is load-bearing rather than decorative.
       */
      id: 'ios-rich-group-scene',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        iosMode: 'imessage',
        iosDarkMode: false,
        iosShowReadReceipt: true,
        iosAutoAlternate: false,
        iosFrameMode: 'header',
        iosScrollable: false,
        iosViewportHeightEm: 34,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        iosGroupMode: true,
        iosGroupName: 'Cabin Weekend',
        iosGroupParticipants: [
          { id: 'p-mara', name: 'Mara', color: '#c8102e', iosTone: 'red' },
          { id: 'p-dev', name: 'Dev', color: '#1b6b2c', iosTone: 'green' },
        ],
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: 'ios-rich-date', sender: '', content: '', outgoing: false, iosEvent: { kind: 'date', text: 'Friday 9:41 PM' } },
        { id: 'ios-rich-1', sender: 'Mara', participantId: 'p-mara', content: 'We are ten minutes out. The road is worse than the map said.', outgoing: false, timestamp: '9:41 PM' },
        { id: 'ios-rich-2', sender: 'Dev', participantId: 'p-dev', content: 'Same. Second gear the whole way up.', outgoing: false, timestamp: '9:42 PM', iosTapbacks: [{ emoji: '😂', count: 2 }] },
        { id: 'ios-rich-3', sender: 'You', content: 'I got here first. Kettle is on.', outgoing: true, timestamp: '9:43 PM', status: 'read', iosReply: { messageId: 'ios-rich-1' } },
        {
          id: 'ios-rich-photos', sender: 'You', content: 'This is what you are driving into.', outgoing: true, timestamp: '9:44 PM', status: 'read',
          attachments: [
            { type: 'image', url: 'https://picsum.photos/id/1015/600/400', alt: 'A river running through a pine valley at dusk' },
            { type: 'image', url: 'https://picsum.photos/id/1016/600/400', alt: 'Fog sitting low across a forested ridge' },
            { type: 'image', url: 'https://picsum.photos/id/1018/600/400', alt: 'A gravel track disappearing between trees' },
            { type: 'image', url: 'https://picsum.photos/id/1019/600/400', alt: 'The cabin porch light on against the dark' },
          ],
        },
        {
          id: 'ios-rich-link', sender: 'Mara', participantId: 'p-mara', content: 'The forecast changed again.', outgoing: false, timestamp: '9:46 PM',
          iosLinkPreview: {
            url: 'https://example.com/mountain-forecast',
            title: 'Mountain forecast — heavy rain overnight',
            siteName: 'example.com',
            description: 'Rain easing after 6am, with low cloud on the pass until midday.',
          },
        },
        {
          id: 'ios-rich-voice', sender: 'Dev', participantId: 'p-dev', content: '', outgoing: false, timestamp: '9:48 PM',
          iosMedia: {
            kind: 'audio',
            url: 'https://archive.org/download/testmp3testfile/mpthreetest.mp3',
            mimeType: 'audio/mpeg',
            duration: '0:09',
            transcript: 'You are not going to believe the size of the deer that just walked across the road.',
          },
        },
        {
          id: 'ios-rich-video', sender: 'You', content: 'Put this on when you get in.', outgoing: true, timestamp: '9:52 PM', status: 'delivered',
          // No poster: an empty poster is the signal to derive the YouTube
          // thumbnail, which is exactly the regression §7.7 asks to pin.
          iosMedia: {
            kind: 'video',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=XlcK4VYSWZk',
            title: 'Rain on a tin roof',
            duration: '3:04',
            description: 'Three hours of rain recorded from a cabin porch.',
          },
        },
        { id: 'ios-rich-system', sender: '', content: '', outgoing: false, iosEvent: { kind: 'system', text: 'Mara named the conversation Cabin Weekend' } },
        { id: 'ios-rich-last', sender: 'Mara', participantId: 'p-mara', content: 'Headlights. We see the porch.', outgoing: false, timestamp: '9:58 PM', showTimeBreak: true, timeBreakText: 'Six minutes later', iosTapbacks: [{ emoji: '❤️' }, { emoji: '👍', count: 2 }] },
      ]
    },
  ],

  // ========== WHATSAPP EXAMPLES (4) ==========
  android: [
    {
      id: 'whatsapp-chat',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: 'Alex',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Alex',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'Alex', content: 'Are you coming to the meeting?', outgoing: false, timestamp: '2:30 PM' },
        { id: '2', sender: 'You', content: "Yes! On my way", outgoing: true, timestamp: '2:32 PM', status: 'delivered' },
        { id: '3', sender: 'Alex', content: 'Great 👍', outgoing: false, timestamp: '2:33 PM' },
        { id: '4', sender: 'Alex', content: 'Bring the files?', outgoing: false, timestamp: '2:33 PM' },
        { id: '5', sender: 'You', content: 'Got them all', outgoing: true, timestamp: '2:34 PM', status: 'read' },
        { id: '6', sender: 'You', content: 'See you in 10 minutes', outgoing: true, timestamp: '2:34 PM', status: 'read' },
      ]
    },
    {
      id: 'whatsapp-profile-picture',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'last seen today at 5:42 PM',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidContactName: 'Mom',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Mom',
        chatShowTyping: false,
        chatTypingName: '',
        androidAvatarUrl: `${AVATAR_CDN}/mom-avatar.png`,
      },
      messages: [
        { id: '1', sender: 'Mom', content: 'Dinner at 6?', outgoing: false, timestamp: '3:15 PM' },
        { id: '2', sender: 'You', content: "Can't, working late", outgoing: true, timestamp: '3:20 PM', status: 'read' },
        { id: '3', sender: 'Mom', content: "You work too hard 😔", outgoing: false, timestamp: '3:21 PM' },
        { id: '4', sender: 'Mom', content: 'I made your favorite', outgoing: false, timestamp: '3:21 PM' },
        { id: '5', sender: 'You', content: '...fine', outgoing: true, timestamp: '3:25 PM', status: 'delivered' },
        { id: '6', sender: 'You', content: "I'll be there at 6", outgoing: true, timestamp: '3:25 PM', status: 'delivered' },
        { id: '7', sender: 'Mom', content: '❤️❤️❤️', outgoing: false, timestamp: '3:26 PM' },
      ]
    },
    {
      id: 'whatsapp-timestamps-receipts',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidContactName: 'Casey',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Casey',
        chatShowTyping: false,
        chatTypingName: '',
        androidAvatarUrl: `${AVATAR_CDN}/Casey-avatar.png`,
      },
      messages: [
        { id: '1', sender: 'You', content: 'Did you send the email?', outgoing: true, timestamp: '9:15 AM', status: 'sent' },
        { id: '2', sender: 'Casey', content: 'Yes! Sent it 5 minutes ago', outgoing: false, timestamp: '9:42 AM' },
        { id: '3', sender: 'You', content: 'Thank you so much', outgoing: true, timestamp: '9:43 AM', status: 'delivered' },
        { id: '4', sender: 'Casey', content: 'No problem', outgoing: false, timestamp: '9:43 AM' },
        { id: '5', sender: 'You', content: 'Did they reply yet?', outgoing: true, timestamp: '10:15 AM', status: 'read' },
        { id: '6', sender: 'Casey', content: 'Not yet', outgoing: false, timestamp: '10:16 AM' },
        { id: '7', sender: 'Casey', content: "I'll let you know when they do", outgoing: false, timestamp: '10:16 AM' },
      ]
    },
    {
      id: 'whatsapp-group-chat',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'tap here for group info',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: 'Squad Goals 🎯',
        androidAutoAlternate: true,
        androidGroupMode: true,
        androidGroupName: 'Squad Goals 🎯',
        androidFrameMode: 'phone',
        androidGroupSubtitleMode: 'members',
        androidScrollable: true,
        androidViewportHeightEm: 34,
        androidGroupParticipants: [
          { id: 'p1', name: 'Alex', color: '#00a884', whatsappTone: 'teal', avatarUrl: `${AVATAR_CDN}/alex-avatar.png` },
          { id: 'p2', name: 'Jordan', color: '#ff5722', whatsappTone: 'orange', avatarUrl: `${AVATAR_CDN}/jordan-avatar.png` },
          { id: 'p3', name: 'Sam', color: '#9c27b0', whatsappTone: 'purple' },
        ],
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Squad Goals 🎯',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: 'day', sender: '', content: '', outgoing: false, whatsappEvent: { kind: 'date', text: 'Tomorrow' } },
        { id: '1', sender: 'Alex', content: 'Anyone free for coffee tomorrow?', outgoing: false, timestamp: '11:30 AM', participantId: 'p1', whatsappReactions: [{ emoji: '☕', count: 3 }] },
        { id: '2', sender: 'Jordan', content: 'I am! What time?', outgoing: false, timestamp: '11:32 AM', participantId: 'p2' },
        { id: '3', sender: 'You', content: 'Count me in 🙋', outgoing: true, timestamp: '11:33 AM', status: 'delivered', whatsappReply: { messageId: '1' } },
        { id: '4', sender: 'Sam', content: 'Can we do 2pm?', outgoing: false, timestamp: '11:35 AM', participantId: 'p3', whatsappLinkPreview: { url: 'https://example.com/cafe', title: 'Corner Cafe', siteName: 'example.com', description: 'Menu and directions.' } },
        { id: '5', sender: 'Alex', content: 'Perfect! Same place as last time?', outgoing: false, timestamp: '11:36 AM', participantId: 'p1', attachments: [
          { type: 'image', url: `${AVATAR_CDN}/alex-avatar.png`, alt: 'Alex outside the cafe' },
          { type: 'image', url: `${AVATAR_CDN}/jordan-avatar.png`, alt: 'Jordan holding two coffee cups' },
        ] },
        { id: 'voice', sender: 'Jordan', content: '', outgoing: false, timestamp: '11:36 AM', participantId: 'p2', whatsappMedia: { kind: 'audio', url: 'https://archive.org/download/testmp3testfile/mpthreetest.mp3', mimeType: 'audio/mpeg', duration: '0:08', transcript: 'I can book us a table.' } },
        { id: 'video', sender: 'You', content: '', outgoing: true, timestamp: '11:37 AM', status: 'read', whatsappMedia: { kind: 'video', source: 'youtube', url: 'https://www.youtube.com/watch?v=XlcK4VYSWZk', duration: '0:12', description: 'A short clip showing the cafe entrance.' } },
        { id: 'notice', sender: '', content: '', outgoing: false, whatsappEvent: { kind: 'system', text: 'Alex changed the group description' } },
      ]
    },
  ],

  // ========== GOOGLE SEARCH EXAMPLES (3) ==========
  google: [
    {
      id: 'google-search-history',
      template: 'google',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#4285F4',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 800,
        useDarkNeutral: true,
        watermark: true,
        googleQuery: 'how to tell if someone likes you',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 1,240,000,000 results',
        googleResultsTime: '0.48 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: '', content: '15 Signs Someone Likes You - Psychology Today', outgoing: false, googleResultUrl: 'https://www.psychologytoday.com/signs-attraction', googleResultDescription: 'Body language, eye contact, and other subtle cues that indicate romantic interest. Learn to decode the signals from psychology experts.' },
        { id: '2', sender: '', content: 'How To Know If Someone Likes You: 10 Undeniable Signs', outgoing: false, googleResultUrl: 'https://www.wikihow.com/Know-if-Someone-Likes-You', googleResultDescription: 'They make time for you, remember small details, and find excuses to be near you. Here are the most reliable indicators backed by research.' },
        { id: '3', sender: '', content: "15 body language signs that they're into you - Insider", outgoing: false, googleResultUrl: 'https://www.insider.com/body-language-signs-someone-likes-you', googleResultDescription: 'From mirroring your movements to leaning in when you talk, these physical cues reveal hidden attraction according to body language experts.' },
      ]
    },
    {
      id: 'google-research-montage',
      template: 'google',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#4285F4',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 800,
        useDarkNeutral: true,
        watermark: true,
        googleQuery: 'missing person Seattle 2024',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 8,450,000 results',
        googleResultsTime: '0.62 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: '', content: 'Seattle Police Department - Missing Persons Unit', outgoing: false, googleResultUrl: 'https://www.seattle.gov/police/missing-persons', googleResultDescription: 'Report a missing person or search current cases in the Seattle area. 24/7 hotline: (206) 684-5582. Updated daily with new information.' },
        { id: '2', sender: '', content: 'Missing Person Alert: Seattle Resident Last Seen Nov 15', outgoing: false, googleResultUrl: 'https://www.seattletimes.com/missing-person-alert-2024', googleResultDescription: 'Police are searching for Alex Morgan, 28, who was last seen leaving Capitol Hill on November 15th. Anyone with information is urged to contact authorities.' },
        { id: '3', sender: '', content: 'How to File a Missing Person Report in Washington State', outgoing: false, googleResultUrl: 'https://www.findlaw.com/missing-person-washington', googleResultDescription: 'Step-by-step guide to reporting a missing person in WA. Includes information about the 24-hour myth, required documentation, and what happens next.' },
      ]
    },
    {
      id: 'google-news-articles',
      template: 'google',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#4285F4',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 800,
        useDarkNeutral: true,
        watermark: true,
        googleQuery: 'Stark Industries controversy 2025',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,580,000 results',
        googleResultsTime: '0.35 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: '',
        iosFooterImageUrl: '',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidHeaderImageUrl: PLATFORM_ASSETS.whatsapp.headerImage,
        androidFooterImageUrl: PLATFORM_ASSETS.whatsapp.footerImage,
        androidAvatarUrl: '',
        androidContactName: '',
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: '', content: 'Stark Industries Faces Federal Investigation - The New York Times', outgoing: false, googleResultUrl: 'https://www.nytimes.com/stark-industries-investigation', googleResultDescription: 'Federal regulators have opened an investigation into Stark Industries following allegations of weapons technology being sold to unauthorized parties. CEO Tony Stark denies all accusations.' },
        { id: '2', sender: '', content: 'Breaking: Stark Industries Stock Plummets 47% Amid Scandal', outgoing: false, googleResultUrl: 'https://www.bloomberg.com/stark-industries-stock-crash', googleResultDescription: 'Shares of Stark Industries dropped dramatically today as investors reacted to news of the federal investigation. Trading was briefly halted due to extreme volatility.' },
        { id: '3', sender: '', content: 'Tony Stark Responds to Controversy in Exclusive Interview', outgoing: false, googleResultUrl: 'https://www.wired.com/tony-stark-interview-2025', googleResultDescription: '"These allegations are completely unfounded," Stark told reporters. "We have always operated within legal parameters and will cooperate fully with any investigation."' },
      ]
    },
  ],
};

const richTwitterSettings: SkinProject['settings'] = {
  bubbleOpacity: 1,
  senderColor: '#1DA1F2',
  receiverColor: '#f5f8fa',
  fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
  maxWidthPx: 600,
  useDarkNeutral: false,
  fictionLabel: true,
  fictionLabelText: 'Fictional scene',
  twitterShowMetrics: true,
  twitterSceneMode: 'timeline',
  twitterTheme: 'light',
};

TEMPLATE_EXAMPLES.twitter.push(
  {
    id: 'twitter-quote-post',
    template: 'twitter',
    settings: { ...richTwitterSettings },
    cast: {
      twitterPrimaryId: 'casey',
      characters: [
        { id: 'casey', name: 'Casey Lin', twitterHandle: 'caseylin', verified: true },
        { id: 'morgan', name: 'Morgan Reed', twitterHandle: 'morganreed' },
      ],
    },
    messages: [{
      id: 'quote-1', characterId: 'casey', sender: 'Casey Lin', outgoing: true,
      content: 'This changes everything.', timestamp: '7:12 PM', twitterLayout: 'expanded',
      twitterQuote: { characterId: 'morgan', text: 'Meet me at the old station at midnight.', timestamp: '6:58 PM' },
      twitterLikes: 418, twitterRetweets: 62, twitterReplies: 19,
    }],
  },
  {
    id: 'twitter-four-image-post',
    template: 'twitter',
    settings: { ...richTwitterSettings },
    cast: { twitterPrimaryId: 'jamie', characters: [{ id: 'jamie', name: 'Jamie Chen', twitterHandle: 'jamiechen' }] },
    messages: [{
      id: 'grid-1', characterId: 'jamie', sender: 'Jamie Chen', outgoing: true,
      content: 'Four clues. One very strange afternoon.', timestamp: '4:04 PM',
      attachments: [1, 2, 3, 4].map(number => ({ type: 'image' as const, url: `https://placehold.co/600x338/e8eef5/536471?text=Clue+${number}`, alt: `Fictional clue photograph ${number}` })),
      twitterMediaCrop: 'fill-width',
    }],
  },
  {
    id: 'twitter-video-post',
    template: 'twitter',
    settings: { ...richTwitterSettings, twitterTheme: 'dim' },
    cast: { twitterPrimaryId: 'rowan', characters: [{ id: 'rowan', name: 'Rowan Vale', twitterHandle: 'rowanvale' }] },
    messages: [{
      id: 'video-1', characterId: 'rowan', sender: 'Rowan Vale', outgoing: true,
      content: 'I caught the greenhouse opening at dawn.', timestamp: '6:10 AM',
      twitterVideo: {
        source: 'direct',
        url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
        mimeType: 'video/mp4',
        posterUrl: 'https://placehold.co/600x338/183447/f7f9f9?text=Flower+at+dawn',
        title: 'Flower opening at dawn',
        duration: '0:30',
        description: 'A time-lapse of a white flower opening against a dark background.',
      },
    }],
  },
  {
    id: 'twitter-long-thread',
    template: 'twitter',
    settings: { ...richTwitterSettings, twitterSceneMode: 'thread', twitterTheme: 'dark' },
    cast: {
      twitterPrimaryId: 'alex',
      characters: [
        { id: 'alex', name: 'Alex Rivers', twitterHandle: 'alexrivers' },
        { id: 'sam', name: 'Sam Ortiz', twitterHandle: 'samortiz' },
      ],
    },
    messages: Array.from({ length: 18 }, (_, index) => ({
      id: `long-${index + 1}`,
      characterId: index % 4 === 3 ? 'sam' : 'alex',
      sender: index % 4 === 3 ? 'Sam Ortiz' : 'Alex Rivers',
      outgoing: index % 4 !== 3,
      content: index === 0 ? 'A long thread built to demonstrate safe hosted-image continuation.' : `Thread entry ${index + 1}: the story continues without losing its parent context.`,
      timestamp: `8:${String(index).padStart(2, '0')} PM`,
      ...(index > 0 ? { parentId: `long-${index}` } : {}),
      twitterReplyHandlesMode: index > 0 ? 'auto' as const : undefined,
    })),
  },
);

// Get example names for UI display
export function getExampleNames(template: string): Array<{id: string; name: string; description: string}> {
  switch(template) {
    case 'twitter':
      return [
        { id: 'twitter-character-thread', name: '🧵 Character Thread', description: 'Multi-part tweet thread with custom profile' },
        { id: 'twitter-verified-account', name: '✓ Verified Account', description: 'Celebrity tweet with engagement stats' },
        { id: 'twitter-media-image', name: '📷 Tweet with Media', description: 'Tweet with attached photo' },
        { id: 'twitter-quote-post', name: '↗ Quote Post', description: 'Per-post quote using a live scene account' },
        { id: 'twitter-four-image-post', name: '▦ Four-Image Grid', description: 'Accessible two-by-two media post' },
        { id: 'twitter-video-post', name: '▶ Video Poster', description: 'Rights-safe video with static export fallback' },
        { id: 'twitter-long-thread', name: '🧵 Long Thread', description: 'Thread that crosses a hosted-export boundary' },
      ];
    case 'ios':
      return [
        { id: 'ios-two-person-chat', name: '💬 Two-Person Chat', description: 'Simple blue bubble conversation' },
        { id: 'ios-contact-avatar', name: '👤 Contact with Avatar', description: 'Chat with profile picture' },
        { id: 'ios-typing-indicators', name: '⋯ Typing Indicators', description: 'Conversation with "..." bubbles' },
        { id: 'ios-rich-group-scene', name: '✦ Rich Group Scene', description: 'Replies, four photos, link, voice, video, Tapbacks and events' },
      ];
    case 'android':
      return [
        { id: 'whatsapp-chat', name: '💚 WhatsApp Chat', description: 'Green bubble conversation' },
        { id: 'whatsapp-profile-picture', name: '📸 With Profile Picture', description: 'Chat with contact photo' },
        { id: 'whatsapp-timestamps-receipts', name: '✓✓ Timestamps & Receipts', description: 'Messages with read status' },
        { id: 'whatsapp-group-chat', name: '🎯 Group Chat', description: 'Multi-participant conversation with avatars' },
      ];
    case 'google':
      return [
        { id: 'google-search-history', name: '❤️ Search History', description: 'Character researching feelings' },
        { id: 'google-research-montage', name: '🔍 Research Montage', description: 'Investigation search results' },
        { id: 'google-news-articles', name: '📰 News Articles', description: 'Fake news headlines for world-building' },
      ];
    default:
      return [];
  }
}

// Load example by ID
export function loadExample(exampleId: string): SkinProject | null {
  for (const template in TEMPLATE_EXAMPLES) {
    const example = TEMPLATE_EXAMPLES[template].find(ex => ex.id === exampleId);
    if (example) return instantiateTemplate(example);
  }
  return null;
}

function freshTemplateProjectId(): string {
  try {
    if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') return crypto.randomUUID();
  } catch { /* use a local fallback */ }
  return `project-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

function cloneProject(project: SkinProject): SkinProject {
  if (typeof structuredClone === 'function') return structuredClone(project);
  return JSON.parse(JSON.stringify(project)) as SkinProject;
}

/**
 * Create an isolated, normalized project from a module-level quick template.
 * Template constants are never returned by reference.
 */
export function instantiateTemplate(example: SkinProject): SkinProject {
  const cloned = cloneProject(example);
  cloned.id = freshTemplateProjectId();
  let project = migrateProjectIdentities(cloned);

  // Current Twitter templates contain only main-account posts. Remove the
  // duplicated legacy preset/message profile so those posts follow one stable
  // scene identity when the main account is edited.
  if (project.template === 'twitter' && project.cast?.twitterPrimaryId) {
    const primaryId = project.cast.twitterPrimaryId;
    project = {
      ...project,
      settings: { ...project.settings, twitterCharacterPresets: [] },
      messages: project.messages.map(message => {
        if (message.characterId !== primaryId) return message;
        const normalized = { ...message, characterId: primaryId, useCustomIdentity: false };
        delete normalized.twitterHandle;
        delete normalized.avatarUrl;
        delete normalized.verified;
        return normalized;
      }),
    };
  }

  const localAvatarUrls = [
    project.settings.iosAvatarUrl,
    project.settings.androidAvatarUrl,
    project.settings.twitterAvatarUrl,
    ...project.messages.map(message => message.avatarUrl),
    ...(project.settings.iosGroupParticipants || []).map(participant => participant.avatarUrl),
    ...(project.settings.androidGroupParticipants || []).map(participant => participant.avatarUrl),
    ...(project.cast?.characters || []).map(character => character.avatarUrl),
  ].filter((value): value is string => !!value && value.startsWith('/'));
  if (localAvatarUrls.some(value => !value.startsWith('/assets/'))) {
    throw new Error('Quick template contains a local avatar outside /assets/.');
  }
  return project;
}
