import { SkinProject } from './schema';

// Pre-defined example conversations matching the Examples Gallery
// Writers can load these as starting points for quick wins

export const TEMPLATE_EXAMPLES: Record<string, SkinProject[]> = {
  // ========== TWITTER/X EXAMPLES (3) ==========
  twitter: [
    {
      id: 'twitter-character-thread',
      template: 'twitter',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#1DA1F2',
        receiverColor: '#f5f8fa',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 600,
        useDarkNeutral: true,
        watermark: true,
        twitterDisplayName: 'Alex Rivers',
        twitterHandle: 'alexrivers',
        twitterVerified: true,
        twitterAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Alex-Rivers-avatar.png',
        twitterShowMetrics: true,
        twitterThreadMode: true,
        twitterTimestamp: '2:15 PM · Nov 26, 2025',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
        twitterCharacterPresets: [
          { id: 'char1', name: 'Alex Rivers', handle: 'alexrivers', verified: true, avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Alex-Rivers-avatar.png' }
        ]
      },
      messages: [
        { id: '1', sender: 'Alex Rivers', content: "okay so I need to tell you all something\n\nthis is going to be a thread 🧵", outgoing: true, timestamp: '2:15 PM', twitterLikes: 847, twitterRetweets: 89, twitterReplies: 156, useCustomIdentity: true, twitterHandle: 'alexrivers', avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Alex-Rivers-avatar.png', verified: true },
        { id: '2', sender: 'Alex Rivers', content: "first of all, I never expected this to happen\n\nbut here we are", outgoing: true, timestamp: '2:16 PM', twitterLikes: 623, twitterRetweets: 34, twitterReplies: 67, parentId: '1', useCustomIdentity: true, twitterHandle: 'alexrivers', avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Alex-Rivers-avatar.png', verified: true },
        { id: '3', sender: 'Alex Rivers', content: "and I know you're all going to have opinions about this\n\nbut honestly? I don't care anymore", outgoing: true, timestamp: '2:18 PM', twitterLikes: 1103, twitterRetweets: 198, twitterReplies: 289, parentId: '2', useCustomIdentity: true, twitterHandle: 'alexrivers', avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Alex-Rivers-avatar.png', verified: true },
      ]
    },
    {
      id: 'twitter-verified-account',
      template: 'twitter',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#1DA1F2',
        receiverColor: '#f5f8fa',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 600,
        useDarkNeutral: true,
        watermark: true,
        twitterDisplayName: 'Taylor Swift',
        twitterHandle: 'taylorswift13',
        twitterVerified: true,
        twitterAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Taylor-Swift-avatar.png',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        twitterTimestamp: '12:00 PM · Nov 26, 2025',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
        twitterCharacterPresets: [
          { id: 'char1', name: 'Taylor Swift', handle: 'taylorswift13', verified: true, avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Taylor-Swift-avatar.png' }
        ]
      },
      messages: [
        { id: '1', sender: 'Taylor Swift', content: "Big news coming tonight at midnight 🌙✨\n\nI can't wait to share this with you all", outgoing: true, timestamp: '12:00 PM', twitterLikes: 2847293, twitterRetweets: 189473, twitterReplies: 45821, twitterViews: 15200000, useCustomIdentity: true, twitterHandle: 'taylorswift13', avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Taylor-Swift-avatar.png', verified: true },
      ]
    },
    {
      id: 'twitter-media-image',
      template: 'twitter',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#1DA1F2',
        receiverColor: '#f5f8fa',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 600,
        useDarkNeutral: true,
        watermark: true,
        twitterDisplayName: 'Jamie Chen',
        twitterHandle: 'jamiechen',
        twitterVerified: false,
        twitterAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Jamie-Chen-avatar.png',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        twitterTimestamp: '5:42 PM · Nov 26, 2025',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
        twitterCharacterPresets: [
          { id: 'char1', name: 'Jamie Chen', handle: 'jamiechen', verified: false, avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Jamie-Chen-avatar.png' }
        ]
      },
      messages: [
        { 
          id: '1', 
          sender: 'Jamie Chen', 
          content: "caught the most incredible sunset today 🌅\n\nsometimes you just have to stop and appreciate the moment", 
          outgoing: true, 
          timestamp: '5:42 PM', 
          twitterLikes: 2431, 
          twitterRetweets: 128, 
          twitterReplies: 89, 
          attachments: [{ type: 'image', url: 'https://media.publit.io/file/AO3-Skins-App/sunset-scene.png' }],
          useCustomIdentity: true, 
          twitterHandle: 'jamiechen', 
          avatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Jamie-Chen-avatar.png', 
          verified: false 
        },
      ]
    },
  ],

  // ========== iOS iMESSAGE EXAMPLES (3) ==========
  ios: [
    {
      id: 'ios-two-person-chat',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: 'Sam',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'Sam', content: 'hey', outgoing: false, timestamp: '10:23' },
        { id: '2', sender: 'You', content: 'hi!', outgoing: true, timestamp: '10:24' },
        { id: '3', sender: 'Sam', content: 'you free tonight?', outgoing: false, timestamp: '10:24' },
        { id: '4', sender: 'You', content: 'yeah why', outgoing: true, timestamp: '10:25' },
        { id: '5', sender: 'Sam', content: 'want to grab dinner?', outgoing: false, timestamp: '10:25' },
        { id: '6', sender: 'You', content: "I'd love to", outgoing: true, timestamp: '10:26', status: 'read' },
      ]
    },
    {
      id: 'ios-contact-avatar',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: 'Jordan',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/jordan-avatar.png',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'Jordan', content: "did you see what they posted?!", outgoing: false, timestamp: '3:15' },
        { id: '2', sender: 'You', content: 'NO what happened', outgoing: true, timestamp: '3:16' },
        { id: '3', sender: 'Jordan', content: "I'm sending you the screenshot", outgoing: false, timestamp: '3:16' },
        { id: '4', sender: 'Jordan', content: "you're not going to believe this", outgoing: false, timestamp: '3:16' },
        { id: '5', sender: 'You', content: 'JORDAN', outgoing: true, timestamp: '3:17' },
        { id: '6', sender: 'You', content: 'TELL ME', outgoing: true, timestamp: '3:17', status: 'read' },
      ]
    },
    {
      id: 'ios-typing-indicators',
      template: 'ios',
      settings: {
        bubbleOpacity: 1.0,
        senderColor: '#007AFF',
        receiverColor: '#E9E9EB',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: 'Riley',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Riley-avatar.png',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'You', content: 'I have something to tell you', outgoing: true, timestamp: '11:47 PM' },
        { id: '2', sender: 'Riley', content: 'okay?', outgoing: false, timestamp: '11:48 PM' },
        { id: '3', sender: 'You', content: "it's about what happened last week", outgoing: true, timestamp: '11:49 PM', status: 'read' },
        { id: '4', sender: 'Riley', content: '...', outgoing: false, timestamp: '', isTyping: true },
      ]
    },
  ],

  // ========== WHATSAPP EXAMPLES (3) ==========
  android: [
    {
      id: 'whatsapp-chat',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: 'Alex',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Alex',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: 'Alex', content: 'Are you coming to the meeting?', outgoing: false, timestamp: '2:30 PM' },
        { id: '2', sender: 'You', content: "Yes! On my way", outgoing: true, timestamp: '2:32 PM', status: 'delivered' },
        { id: '3', sender: 'Alex', content: 'Great 👍', outgoing: false, timestamp: '2:33 PM' },
        { id: '4', sender: 'Alex', content: 'Bring the files?', outgoing: false, timestamp: '2:33 PM' },
        { id: '5', sender: 'You', content: 'Got them all', outgoing: true, timestamp: '2:34 PM', status: 'read' },
        { id: '6', sender: 'You', content: 'See you in 10 minutes', outgoing: true, timestamp: '2:34 PM', status: 'read' },
      ]
    },
    {
      id: 'whatsapp-profile-picture',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'last seen today at 5:42 PM',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: 'Mom',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Mom',
        chatShowTyping: false,
        chatTypingName: '',
        instagramAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/mom-avatar.png',
      },
      messages: [
        { id: '1', sender: 'Mom', content: 'Dinner at 6?', outgoing: false, timestamp: '3:15 PM' },
        { id: '2', sender: 'You', content: "Can't, working late", outgoing: true, timestamp: '3:20 PM', status: 'read' },
        { id: '3', sender: 'Mom', content: "You work too hard 😔", outgoing: false, timestamp: '3:21 PM' },
        { id: '4', sender: 'Mom', content: 'I made your favorite', outgoing: false, timestamp: '3:21 PM' },
        { id: '5', sender: 'You', content: '...fine', outgoing: true, timestamp: '3:25 PM', status: 'delivered' },
        { id: '6', sender: 'You', content: "I'll be there at 6", outgoing: true, timestamp: '3:25 PM', status: 'delivered' },
        { id: '7', sender: 'Mom', content: '❤️❤️❤️', outgoing: false, timestamp: '3:26 PM' },
      ]
    },
    {
      id: 'whatsapp-timestamps-receipts',
      template: 'android',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#dcf8c6',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 400,
        useDarkNeutral: true,
        watermark: true,
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: 'Casey',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        googleQuery: '',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,040,000,000 results',
        googleResultsTime: '0.56 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        chatContactName: 'Casey',
        chatShowTyping: false,
        chatTypingName: '',
        instagramAvatarUrl: 'https://media.publit.io/file/AO3-Skins-App/Casey-avatar.png',
      },
      messages: [
        { id: '1', sender: 'You', content: 'Did you send the email?', outgoing: true, timestamp: '9:15 AM', status: 'sent' },
        { id: '2', sender: 'Casey', content: 'Yes! Sent it 5 minutes ago', outgoing: false, timestamp: '9:42 AM' },
        { id: '3', sender: 'You', content: 'Thank you so much', outgoing: true, timestamp: '9:43 AM', status: 'delivered' },
        { id: '4', sender: 'Casey', content: 'No problem', outgoing: false, timestamp: '9:43 AM' },
        { id: '5', sender: 'You', content: 'Did they reply yet?', outgoing: true, timestamp: '10:15 AM', status: 'read' },
        { id: '6', sender: 'Casey', content: 'Not yet', outgoing: false, timestamp: '10:16 AM' },
        { id: '7', sender: 'Casey', content: "I'll let you know when they do", outgoing: false, timestamp: '10:16 AM' },
      ]
    },
  ],

  // ========== GOOGLE SEARCH EXAMPLES (3) ==========
  google: [
    {
      id: 'google-search-history',
      template: 'google',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#4285F4',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 800,
        useDarkNeutral: true,
        watermark: true,
        googleQuery: 'how to tell if someone likes you',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 1,240,000,000 results',
        googleResultsTime: '0.48 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: '', content: '15 Signs Someone Likes You - Psychology Today', outgoing: false, googleResultUrl: 'https://www.psychologytoday.com/signs-attraction', googleResultDescription: 'Body language, eye contact, and other subtle cues that indicate romantic interest. Learn to decode the signals from psychology experts.' },
        { id: '2', sender: '', content: 'How To Know If Someone Likes You: 10 Undeniable Signs', outgoing: false, googleResultUrl: 'https://www.wikihow.com/Know-if-Someone-Likes-You', googleResultDescription: 'They make time for you, remember small details, and find excuses to be near you. Here are the most reliable indicators backed by research.' },
        { id: '3', sender: '', content: "15 body language signs that they're into you - Insider", outgoing: false, googleResultUrl: 'https://www.insider.com/body-language-signs-someone-likes-you', googleResultDescription: 'From mirroring your movements to leaning in when you talk, these physical cues reveal hidden attraction according to body language experts.' },
      ]
    },
    {
      id: 'google-research-montage',
      template: 'google',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#4285F4',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 800,
        useDarkNeutral: true,
        watermark: true,
        googleQuery: 'missing person Seattle 2024',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 8,450,000 results',
        googleResultsTime: '0.62 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: '', content: 'Seattle Police Department - Missing Persons Unit', outgoing: false, googleResultUrl: 'https://www.seattle.gov/police/missing-persons', googleResultDescription: 'Report a missing person or search current cases in the Seattle area. 24/7 hotline: (206) 684-5582. Updated daily with new information.' },
        { id: '2', sender: '', content: 'Missing Person Alert: Seattle Resident Last Seen Nov 15', outgoing: false, googleResultUrl: 'https://www.seattletimes.com/missing-person-alert-2024', googleResultDescription: 'Police are searching for Alex Morgan, 28, who was last seen leaving Capitol Hill on November 15th. Anyone with information is urged to contact authorities.' },
        { id: '3', sender: '', content: 'How to File a Missing Person Report in Washington State', outgoing: false, googleResultUrl: 'https://www.findlaw.com/missing-person-washington', googleResultDescription: 'Step-by-step guide to reporting a missing person in WA. Includes information about the 24-hour myth, required documentation, and what happens next.' },
      ]
    },
    {
      id: 'google-news-articles',
      template: 'google',
      settings: {
        bubbleOpacity: 0.9,
        senderColor: '#4285F4',
        receiverColor: '#ffffff',
        fontFamily: 'Arial, Helvetica, sans-serif',
        maxWidthPx: 800,
        useDarkNeutral: true,
        watermark: true,
        googleQuery: 'Stark Industries controversy 2025',
        googleSuggestions: [],
        googleShowStats: true,
        googleResultsCount: 'About 24,580,000 results',
        googleResultsTime: '0.35 seconds',
        googleShowDidYouMean: false,
        googleDidYouMean: '',
        googleEngineVariant: 'google',
        iosMode: 'imessage',
        iosContactName: '',
        iosShowReadReceipt: true,
        iosAutoAlternate: true,
        iosShowStatusBar: false,
        iosStatusBarTime: '9:41',
        iosShowInputBar: false,
        iosInputPlaceholder: 'iMessage',
        iosHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-header.png',
        iosFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/imessage-footer.jpg',
        iosAvatarUrl: '',
        androidShowStatus: true,
        androidStatusText: 'online',
        androidCheckmarks: true,
        androidWhatsAppMode: true,
        androidHeaderImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatapp-header.png',
        androidFooterImageUrl: 'https://media.publit.io/file/AO3-Skins-App/whatsapp-footer.png',
        androidAvatarUrl: '',
        androidContactName: '',
        androidShowReadReceipt: true,
        androidAutoAlternate: true,
        twitterDisplayName: '',
        twitterHandle: '',
        twitterVerified: false,
        twitterAvatarUrl: '',
        twitterShowMetrics: true,
        twitterThreadMode: false,
        chatContactName: '',
        chatShowTyping: false,
        chatTypingName: '',
      },
      messages: [
        { id: '1', sender: '', content: 'Stark Industries Faces Federal Investigation - The New York Times', outgoing: false, googleResultUrl: 'https://www.nytimes.com/stark-industries-investigation', googleResultDescription: 'Federal regulators have opened an investigation into Stark Industries following allegations of weapons technology being sold to unauthorized parties. CEO Tony Stark denies all accusations.' },
        { id: '2', sender: '', content: 'Breaking: Stark Industries Stock Plummets 47% Amid Scandal', outgoing: false, googleResultUrl: 'https://www.bloomberg.com/stark-industries-stock-crash', googleResultDescription: 'Shares of Stark Industries dropped dramatically today as investors reacted to news of the federal investigation. Trading was briefly halted due to extreme volatility.' },
        { id: '3', sender: '', content: 'Tony Stark Responds to Controversy in Exclusive Interview', outgoing: false, googleResultUrl: 'https://www.wired.com/tony-stark-interview-2025', googleResultDescription: '"These allegations are completely unfounded," Stark told reporters. "We have always operated within legal parameters and will cooperate fully with any investigation."' },
      ]
    },
  ],
};

// Get example names for UI display
export function getExampleNames(template: string): Array<{id: string; name: string; description: string}> {
  switch(template) {
    case 'twitter':
      return [
        { id: 'twitter-character-thread', name: '🧵 Character Thread', description: 'Multi-part tweet thread with custom profile' },
        { id: 'twitter-verified-account', name: '✓ Verified Account', description: 'Celebrity tweet with engagement stats' },
        { id: 'twitter-media-image', name: '📷 Tweet with Media', description: 'Tweet with attached photo' },
      ];
    case 'ios':
      return [
        { id: 'ios-two-person-chat', name: '💬 Two-Person Chat', description: 'Simple blue bubble conversation' },
        { id: 'ios-contact-avatar', name: '👤 Contact with Avatar', description: 'Chat with profile picture' },
        { id: 'ios-typing-indicators', name: '⋯ Typing Indicators', description: 'Conversation with "..." bubbles' },
      ];
    case 'android':
      return [
        { id: 'whatsapp-chat', name: '💚 WhatsApp Chat', description: 'Green bubble conversation' },
        { id: 'whatsapp-profile-picture', name: '📸 With Profile Picture', description: 'Chat with contact photo' },
        { id: 'whatsapp-timestamps-receipts', name: '✓✓ Timestamps & Receipts', description: 'Messages with read status' },
      ];
    case 'google':
      return [
        { id: 'google-search-history', name: '❤️ Search History', description: 'Character researching feelings' },
        { id: 'google-research-montage', name: '🔍 Research Montage', description: 'Investigation search results' },
        { id: 'google-news-articles', name: '📰 News Articles', description: 'Fake news headlines for world-building' },
      ];
    default:
      return [];
  }
}

// Load example by ID
export function loadExample(exampleId: string): SkinProject | null {
  for (const template in TEMPLATE_EXAMPLES) {
    const example = TEMPLATE_EXAMPLES[template].find(ex => ex.id === exampleId);
    if (example) return example;
  }
  return null;
}
